export enum ActionTypes {
  UPDATE_PASSWORDS_STATE = "UPDATE_PASSWORDS_STATE",
  UPDATE_CHARACTERS = "UPDATE_CHARACTERS",
  GENERATE_PASSWORD = "GENERATE_PASSWORD",
  CLEAR_PASSWORDS_STATE = "CLEAR_PASSWORDS_STATE",
  OPEN_MODAL = "OPEN_MODAL",
  CLOSE_MODAL = "CLOSE_MODAL",
}
